### ISSUE TITLE
Html Entities Unsupported

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-test#51]
While writing the benchmarks project, I ran into an issue where Html Entities cause the following:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Xml.XmlException: Reference to undeclared entity 'copy'. Line 82, position 67.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at System.Xml.XmlSubtreeReader.Read()
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-test\Mjml.Net\MjmlRenderContext.cs:line 120
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-test\Mjml.Net\MjmlRenderContext.cs:line 146
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-test\Mjml.Net\MjmlRenderContext.cs:line 146
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-test\Mjml.Net\MjmlRenderContext.cs:line 146
   at Mjml.Net.MjmlRenderContext.ReadElement(String name, XmlReader parentReader, IComponent parent) in C:\Source\mjml-test\Mjml.Net\MjmlRenderContext.cs:line 146
   at Mjml.Net.MjmlRenderContext.Read(XmlReader reader) in C:\Source\mjml-test\Mjml.Net\MjmlRenderContext.cs:line 56
```

**Comment by SebastianStehle** [comment]
Weird, are you going to have a look?

**Comment by LiamRiddell** [comment]
> Weird, are you going to have a look?

I believe this is the issue I ran into when I was trying XmlReader in my implementation. I'm googling around to see if there is any smart solution.

**Comment by LiamRiddell** [comment]
@SebastianStehle from my research and tests we have three solutions so far:

1. Change nothing and inform users to use the **Entity Number** instead of **Entity Names** e.g. `&copy;` -> `&#169;`
2. We can change DtdProcessing to `Parse` with Security Settings and we prepend the incoming text/stream with a list of common **Entity Names**.
```csharp
// Secure XmlReaderSettings for DtdProcessing
xmlReaderSettings = new ()
{
    DtdProcessing = DtdProcessing.Parse, // Secure by the below two properties
    MaxCharactersFromEntities = 1024, // Prevent XML DoS Attack
    XmlResolver = null // Prevent XXE Attacks
};
```
Inject at top of document content
```
<!DOCTYPE HTML [
<!ENTITY copy "&#169;">
<!ENTITY nbsp "&#169;">
]
```
3. Replace the incoming content with a mapping table of `EntityName` to `EntityCode`.

Since the both 2 and 3 require additional processing power and have a security risk. I think it's safer and more optimized to go with solution 1.

**Comment by SebastianStehle** [comment]
We could just introduce a setting for that? I think &copy is really common.

**Comment by LiamRiddell** [comment]
> We could just introduce a setting for that? I think &copy is really common.

I'll do some research on a common list of HTML Entites. I think maybe the top 10. However, how would we replace the entities when using MjmlRenderer constructor with the Stream?

**Comment by SebastianStehle** [comment]
I mean we could just introduce a setting and live with the security issue.

**Comment by LiamRiddell** [comment]
> I mean we could just introduce a setting and live with the security issue.

The security issue does not fix the problem. It's a two part fix. So we have to set `DtdProcessing` to `Parse` and then also you'd need to include the following at the start of the MJML template:

```
<!DOCTYPE HTML [
<!ENTITY copy "&#169;">
<!ENTITY nbsp "&#169;">
]
```
Which should include any of the other entity definitions. However, I think at that point it would be easier for the user to just covert to Entity Number instead of Entity Name manually in the template.

**Comment by SebastianStehle** [comment]
I see, then we have to live with it I guess :(

**Comment by LiamRiddell** [comment]
> I see, then we have to live with it I guess :(

Yeah, unfortunately. I think we will. I'll update readme with a "Limitations" section and add this problem and the solution.

**Comment by LiamRiddell** [comment]
I found that using reflection we can disable the field `DisableUndeclaredEntityCheck` on the `XmlReader` and this prevents the rendering from crashing but the entity is omitted from the output. Would it be worth implementing this?

**Comment by SebastianStehle** [comment]
No, I don't think so. It is even worse when errors are swallowed.
